apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: "{{ .Release.Name }}-{{ .Release.Revision }}"
spec:
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  type: {{ .Values.service.type }}
  ports:
    {{ range .Values.service.ports }}
    - name: "{{ . }}"
      port: {{ . }}
      protocol: TCP
    {{ end }}
