
spec:
  template:
    metadata:
      labels:
        {{ .PatchedLabelName }}: "true"
    spec:
      containers:
      - name: {{ .ContainerName }}
        image: {{ .Image }}
        command:
        args:
        livenessProbe:
        readinessProbe:
        volumeMounts:
          - mountPath: {{ .MountPath }}
            name: "{{ .ContainerName }}-patch-mount"
        ports:
          - name: delve
            containerPort: 2345
            protocol: TCP
      volumes:
        - name: "{{ .ContainerName }}-patch-mount"
          hostPath:
            path: {{ .HostPath }}